# Generated by Django 4.2.1 on 2023-05-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=255)),
                ('userName', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('isTweetImage', models.BooleanField(default=False)),
                ('tweetImage', models.CharField(blank=True, max_length=255, null=True)),
                ('timings', models.CharField(max_length=255)),
                ('comments', models.IntegerField(default=0)),
                ('retweets', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('tuits', models.CharField(max_length=255)),
                ('isContentBelowPost', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('gold', models.BooleanField(default=False)),
                ('retweet', models.BooleanField(default=False)),
                ('retweetBy', models.CharField(blank=True, max_length=255, null=True)),
                ('liked', models.BooleanField(default=False)),
                ('dislikes', models.IntegerField(default=0)),
                ('disliked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tuits',
            },
        ),
    ]
