# Generated by Django 4.2.1 on 2023-05-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuit',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tuit',
            name='handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tuit',
            name='timings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tuit',
            name='tuits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tuit',
            name='userName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
